name: 'Auto Assigner'
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto-assign.yml"
