name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to the project! Thank you for raising this issue. A maintainer will review it shortly. In the meantime, feel free to explore the code!"
          pr-message: "🚀 Thank you for creating this Pull Request! We appreciate your support. We will review your changes as soon as possible. Please ensure you have run local tests!"

      - name: Add Label to Issue
        if: github.event_name == 'issues'
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            })