name: Lighthouse Badge
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Badge Gen
        run: echo "Badge generator ready for next CI run."
