name: PR Size Labeler
on: [pull_request]
jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: pascalgn/size-label-action@v0.5.7
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
