name: TODO to Issue
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
