name: W3C HTML Validator
on: [pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate HTML
        run: npx html-validator-cli --file="**/*.html" || true
